In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data = pd.read_csv("iris.csv")

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
data = data.drop("Id",axis =1)

In [6]:
data.shape

(150, 5)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
data.Species.value_counts()

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: Species, dtype: int64

In [9]:
x = data.drop("Species",axis = 1)
y = data['Species']

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
x_train, x_val, y_train, y_val= train_test_split(x_train, y_train, test_size=0.25, random_state=42)

In [11]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

1.0

In [12]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

1.0

In [13]:
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

1.0

In [14]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9666666666666667

In [15]:
from sklearn.model_selection import StratifiedKFold

In [16]:
folds = StratifiedKFold(n_splits=10)

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
(cross_val_score(LogisticRegression(solver = "liblinear"),x_val,y_val))

array([1.        , 0.66666667, 0.83333333, 0.66666667, 0.66666667])

In [19]:
(cross_val_score(SVC(),x_val,y_val))

array([1.        , 0.83333333, 0.83333333, 0.83333333, 1.        ])

In [20]:
cross_val_score(KNeighborsClassifier(),x_val,y_val)

array([1.        , 0.83333333, 0.83333333, 0.83333333, 1.        ])

In [21]:
cross_val_score(RandomForestClassifier(),x_val,y_val)

array([1., 1., 1., 1., 1.])

In [22]:
rfc = RandomForestClassifier()
model = rfc.fit(x_train,y_train)
y_predict = rfc.predict(x_test)


In [24]:
print("enter the values:")
sepal_length = float(input("sepal_width : "))
sepal_width = float(input("sepal_width: "))
petal_length = float(input("petal_width: "))
petal_width = float(input("petal_width: "))

#predicting
output =  rfc.predict([[sepal_length,sepal_width,petal_length,petal_width]])
output

enter the values:
sepal_width : 4
sepal_width: 5
petal_width: 5
petal_width: 5


array(['Iris-virginica'], dtype=object)